### Create a home
POST http://localhost:3000/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWxhbiIsImlkIjoiYWVhMzhlZTMtMGYyNS00ZjdhLWEwNjYtZGRlMTY3MmE1YjE3IiwiaWF0IjoxNjg4Njc2OTg0LCJleHAiOjE2ODg3NjMzODR9.lydUgasTO2pBZwRvh2WcZF5j46S422pzckQtVw-r4pE
Content-Type: application/json

{
 "address": "Rua y",
"numberOfBedrooms": 2,
"numberOfBathrooms": 3,
"city": "Cidade X",
"price": 1000000,
"landSize": 360000,
"propertyType": "CONDO",
"images": [
  {
    "url": "image1"
  },
  {
    "url": "image2"
  }
]
}

# query params
# city --> string
# minPrice --> number
# maxPrice --> number
# propertyType --> CONDO | RESIDENTIAL
### Get all homes
GET http://localhost:3000/home?

### Get a home by id
GET http://localhost:3000/home/123

### Edit a home by id
PUT http://localhost:3000/home/2e47ef87-3a6e-42d1-b18c-14820d913043
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWxhbiIsImlkIjoiYWVhMzhlZTMtMGYyNS00ZjdhLWEwNjYtZGRlMTY3MmE1YjE3IiwiaWF0IjoxNjg4Njc2OTg0LCJleHAiOjE2ODg3NjMzODR9.lydUgasTO2pBZwRvh2WcZF5j46S422pzckQtVw-r4pE
Content-Type: application/json

{
 "address": "Rua y",
"numberOfBedrooms": 2,
"numberOfBathrooms": 3,
"city": "Cidade X",
"price": 1000000,
"landSize": 360000,
"propertyType": "RESIDENTIAL"
}

### Delete a home by id
DELETE  http://localhost:3000/home/072d8684-d0bf-4d4f-ac4a-e4d2c9e1ee6b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWxhbiIsImlkIjoiYWVhMzhlZTMtMGYyNS00ZjdhLWEwNjYtZGRlMTY3MmE1YjE3IiwiaWF0IjoxNjg4Njc2OTg0LCJleHAiOjE2ODg3NjMzODR9.lydUgasTO2pBZwRvh2WcZF5j46S422pzckQtVw-r4pE

### Create a message
POST http://localhost:3000/home/48f246ec-6957-49f6-a08a-622fb0a1dc34/inquire
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWxhbiIsImlkIjoiYTBiNDBhZWUtYzE3YS00ZTg3LThmOTEtNTkwMTM2NjE3YmM4IiwiaWF0IjoxNjg4Njk2NzgyLCJleHAiOjE2ODg3ODMxODJ9.fOG3782AvocwJTFEAQjl8HK60bGxCkncPHkygrAGSow
Content-Type: application/json

{
  "message": "Mensagem de teste"
}

### Create a message
GET http://localhost:3000/home/48f246ec-6957-49f6-a08a-622fb0a1dc34/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWxhbiIsImlkIjoiYWVhMzhlZTMtMGYyNS00ZjdhLWEwNjYtZGRlMTY3MmE1YjE3IiwiaWF0IjoxNjg4Njk3Mzg1LCJleHAiOjE2ODg3ODM3ODV9.2fTUBM08zAfGNyVaOsnVllWzevVIrWwV2rCOCvHiW6k