### Create a home
POST http://localhost:3000/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWxhbiIsImlkIjoiYWVhMzhlZTMtMGYyNS00ZjdhLWEwNjYtZGRlMTY3MmE1YjE3IiwiaWF0IjoxNjg4Njc2OTg0LCJleHAiOjE2ODg3NjMzODR9.lydUgasTO2pBZwRvh2WcZF5j46S422pzckQtVw-r4pE
Content-Type: application/json

{
 "address": "Rua y",
"numberOfBedrooms": 2,
"numberOfBathrooms": 3,
"city": "Cidade X",
"price": 1000000,
"landSize": 360000,
"propertyType": "CONDO",
"images": [
  {
    "url": "image1"
  },
  {
    "url": "image2"
  }
]
}

# query params
# city --> string
# minPrice --> number
# maxPrice --> number
# propertyType --> CONDO | RESIDENTIAL
### Get all homes
GET http://localhost:3000/home?

### Get a home by id
GET http://localhost:3000/home/123

### Edit a home by id
PUT http://localhost:3000/home/072d8684-d0bf-4d4f-ac4a-e4d2c9e1ee6b
Content-Type: application/json

{
 "address": "Rua y",
"numberOfBedrooms": 2,
"numberOfBathrooms": 3,
"city": "Cidade X",
"price": 1000000,
"landSize": 360000,
"propertyType": "RESIDENTIAL"
}

### Delete a home by id
DELETE  http://localhost:3000/home/072d8684-d0bf-4d4f-ac4a-e4d2c9e1ee6b